services:
  database:
    image: 'postgres:latest'
    ports:
      - 5455:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  mock-identity-system:
    image: 'mosipdev/mock-identity-system:develop'
    user: root
    ports:
      - 8082:8082
    environment:
      - container_user=mosip
      - active_profile_env=local
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/mosip_mockidentitysystem?currentSchema=mockidentitysystem
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - database

  esignet:
    build:
      context: ../esignet-service
      dockerfile: Dockerfile
    user: root
    ports: 
      - 8088:8088
    environment:
      - container_user=mosip
      - active_profile_env=local
      - plugin_name_env=esignet-mock-plugin.jar
      - KAFKA_ENABLED=false
      - SPRING_AUTOCONFIGURE_EXCLUDE=org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/mosip_esignet?currentSchema=esignet
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_CACHE_TYPE=simple
      - MOCK_IDENTITY_SYSTEM_DOMAIN_URL=http://mock-identity-system:8082
    depends_on:
      - database