modules:
  esignet:
    enabled: true
    image:
      repository: mosipqa/apitest-esignet
      tag: 1.6.x
      pullPolicy: Always

extraEnvVarsCM:
  - global
  - s3
  - keycloak-host
  - db
  - apitestrig

resources:
  limits:
    cpu: 300m
    memory: 500Mi
  requests:
    cpu: 300m
    memory: 500Mi

